package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

type AutoGenerated struct {
		Name      string    `json:"name"`
		Height    string    `json:"height"`
		Mass      string    `json:"mass"`
	}



func main() {
		response, err := http.Get("https://swapi.co/api/people/1/?format=json")
	if err != nil {
		fmt.Print(err.Error())
		os.Exit(1)
	}

	responseData, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}

	var responseObject AutoGenerated
	json.Unmarshal(responseData, &responseObject)
	fmt.Println("Miljøstasjoner:")
	fmt.Println("Name: ",responseObject.Name)
	fmt.Println("Height in cm: ",responseObject.Height)
	fmt.Println("Weight in kg: ",responseObject.Mass)
}
