package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

type AutoGenerated struct {
	Month      string `json:"month"`
	Num        int    `json:"num"`
	Link       string `json:"link"`
	Year       string `json:"year"`
	News       string `json:"news"`
	SafeTitle  string `json:"safe_title"`
	Transcript string `json:"transcript"`
	Alt        string `json:"alt"`
	Img        string `json:"img"`
	Title      string `json:"title"`
	Day        string `json:"day"`
}


func main() {
	response, err := http.Get("https://xkcd.com/info.0.json")
	if err != nil {
		fmt.Print(err.Error())
		os.Exit(1)
	}

	responseData, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}

	var responseObject AutoGenerated
	json.Unmarshal(responseData, &responseObject)
	fmt.Println("Latest Comic: ")
	fmt.Println("title: ",responseObject.SafeTitle)
	fmt.Println("image url: ",responseObject.Img)
	fmt.Println("year: ",responseObject.Year)
	fmt.Println("month: ",responseObject.Month)
	fmt.Println("day: ",responseObject.Day)


}