package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

type AutoGenerated struct {
	Title    string `json:"title"`
	Homepage string `json:"homepage"`
}


func main() {
	response, err := http.Get("https://data.norge.no/api/dcat/data.json?page=1")
	if err != nil {
		fmt.Print(err.Error())
		os.Exit(1)
	}

	responseData, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}

	var responseObject AutoGenerated
	json.Unmarshal(responseData, &responseObject)
	fmt.Println("Data Norge: ")
	fmt.Println("Title: ",responseObject.Title)
	fmt.Println("Hompage: ",responseObject.Homepage)
}